services:
  app:
    container_name: app
    image: matfin/personal-website-app:latest
    restart: on-failure
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
      args:
        - CANONICAL_URL=https://mattfinucane.build
        - ENABLE_CACHE='true'
    volumes:
      - static-content:/opt/app/dist
    command: yarn deploy

  nginx:
    container_name: nginx
    image: matfin/personal-website-nginx:latest
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - NGINX_HOST=mattfinucane.build
      - SSL_CERTIFICATE=server.crt
      - SSL_CERTIFICATE_KEY=server.key
    links:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/ssl/letsencrypt:/etc/letsencrypt:ro
      - static-content:/opt/public:ro
    command: nginx -g "daemon off;"

volumes:
  static-content:
