version: '3'

services:
  app:
    container_name: app
    image: matfin/personal-website-app:latest
    restart: on-failure
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    environment:
      - API_URL=https://mattfinucane.build
      - CANONICAL_URL=https://mattfinucane.build
      - PORT=3001
      - ENABLE_CACHE=true
    command: yarn prodserver

  nginx:
    container_name: nginx
    image: matfin/personal-website-nginx:latest
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - NGINX_HOST=mattfinucane.build
      - SSL_CERTIFICATE=server.crt
      - SSL_CERTIFICATE_KEY=server.key
      - PROXY_APP_PORT=3001
    links:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/ssl/letsencrypt:/etc/letsencrypt:ro
    command: nginx -g "daemon off;"
