export const FETCH_STORIES_PENDING: string = 'FETCH_STORIES_PENDING';
export const FETCH_STORIES_SUCCESS: string = 'FETCH_STORIES_SUCCESS';
export const FETCH_STORIES_FAILURE: string = 'FETCH_STORIES_FAILURE';
