enum ActionTypes {
  FETCH_PAGE_REQUEST = 'FETCH_PAGE_REQUEST',
  FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS',
  FETCH_PAGE_FAILURE = 'FETCH_PAGE_FAILURE',
  RESET_PAGE = 'RESET_PAGE',
}

export default ActionTypes;
